import { PatienCardProps } from "@/types";

export const patientsList: PatienCardProps[] = [
	{
		id: "1",
		img: "/images/user.png",
		gender: "Male",
		firstName: "John",
		lastName: "Doe",
		adress: "123 Main St, Anytown, USA",
		weight: "75 kg",
		bloodPressure: "120/80 mmHg",
		bloodGlucose: "90 mg/dL",
	},
	{
		id: "2",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Jane",
		lastName: "Smith",
		adress: "456 Elm St, Anytown, USA",
		weight: "60 kg",
		bloodPressure: "110/70 mmHg",
		bloodGlucose: "85 mg/dL",
	},
	{
		id: "3",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Michael",
		lastName: "Johnson",
		adress: "789 Oak St, Anytown, USA",
		weight: "80 kg",
		bloodPressure: "130/85 mmHg",
		bloodGlucose: "95 mg/dL",
	},
	{
		id: "4",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Emily",
		lastName: "Davis",
		adress: "101 Pine St, Anytown, USA",
		weight: "55 kg",
		bloodPressure: "115/75 mmHg",
		bloodGlucose: "80 mg/dL",
	},
	{
		id: "5",
		img: "/images/user.png",
		gender: "Male",
		firstName: "William",
		lastName: "Brown",
		adress: "202 Cedar St, Anytown, USA",
		weight: "70 kg",
		bloodPressure: "125/80 mmHg",
		bloodGlucose: "90 mg/dL",
	},
	{
		id: "6",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Olivia",
		lastName: "Wilson",
		adress: "303 Maple St, Anytown, USA",
		weight: "65 kg",
		bloodPressure: "110/70 mmHg",
		bloodGlucose: "85 mg/dL",
	},
	{
		id: "7",
		img: "/images/user.png",
		gender: "Male",
		firstName: "James",
		lastName: "Moore",
		adress: "404 Birch St, Anytown, USA",
		weight: "85 kg",
		bloodPressure: "135/85 mmHg",
		bloodGlucose: "95 mg/dL",
	},
	{
		id: "8",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Sophia",
		lastName: "Taylor",
		adress: "505 Spruce St, Anytown, USA",
		weight: "50 kg",
		bloodPressure: "115/75 mmHg",
		bloodGlucose: "80 mg/dL",
	},
	{
		id: "9",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Benjamin",
		lastName: "Anderson",
		adress: "606 Fir St, Anytown, USA",
		weight: "75 kg",
		bloodPressure: "120/80 mmHg",
		bloodGlucose: "90 mg/dL",
	},
	{
		id: "10",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Emma",
		lastName: "Thomas",
		adress: "707 Aspen St, Anytown, USA",
		weight: "60 kg",
		bloodPressure: "110/70 mmHg",
		bloodGlucose: "85 mg/dL",
	},
	{
		id: "11",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Daniel",
		lastName: "Jackson",
		adress: "808 Willow St, Anytown, USA",
		weight: "80 kg",
		bloodPressure: "130/85 mmHg",
		bloodGlucose: "95 mg/dL",
	},
	{
		id: "12",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Ava",
		lastName: "White",
		adress: "909 Cypress St, Anytown, USA",
		weight: "55 kg",
		bloodPressure: "115/75 mmHg",
		bloodGlucose: "80 mg/dL",
	},
	{
		id: "13",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Matthew",
		lastName: "Harris",
		adress: "1010 Juniper St, Anytown, USA",
		weight: "70 kg",
		bloodPressure: "125/80 mmHg",
		bloodGlucose: "90 mg/dL",
	},
	{
		id: "14",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Mia",
		lastName: "Martin",
		adress: "1111 Redwood St, Anytown, USA",
		weight: "65 kg",
		bloodPressure: "110/70 mmHg",
		bloodGlucose: "85 mg/dL",
	},
	{
		id: "15",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Henry",
		lastName: "Thompson",
		adress: "1212 Sequoia St, Anytown, USA",
		weight: "85 kg",
		bloodPressure: "135/85 mmHg",
		bloodGlucose: "95 mg/dL",
	},
	{
		id: "16",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Charlotte",
		lastName: "Garcia",
		adress: "1313 Alder St, Anytown, USA",
		weight: "50 kg",
		bloodPressure: "115/75 mmHg",
		bloodGlucose: "80 mg/dL",
	},
	{
		id: "17",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Alexander",
		lastName: "Martinez",
		adress: "1414 Birch St, Anytown, USA",
		weight: "75 kg",
		bloodPressure: "120/80 mmHg",
		bloodGlucose: "90 mg/dL",
	},
	{
		id: "18",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Amelia",
		lastName: "Robinson",
		adress: "1515 Cedar St, Anytown, USA",
		weight: "60 kg",
		bloodPressure: "110/70 mmHg",
		bloodGlucose: "85 mg/dL",
	},
	{
		id: "19",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Samuel",
		lastName: "Clark",
		adress: "1616 Pine St, Anytown, USA",
		weight: "80 kg",
		bloodPressure: "130/85 mmHg",
		bloodGlucose: "95 mg/dL",
	},
	{
		id: "20",
		img: "/images/user.png",
		gender: "Female",
		firstName: "Grace",
		lastName: "Rodriguez",
		adress: "1717 Oak St, Anytown, USA",
		weight: "55 kg",
		bloodPressure: "115/75 mmHg",
		bloodGlucose: "80 mg/dL",
	},
	{
		id: "21",
		img: "/images/user.png",
		gender: "Male",
		firstName: "Joseph",
		lastName: "Lewis",
		adress: "1818 Elm St, Anytown, USA",
		weight: "70 kg",
		bloodPressure: "125/80 mmHg",
		bloodGlucose: "90 mg/dL",
	},
];
